//! Stable 128-bit identity used for workloads, checkpoints, and lineage links.

use std::fmt;
use std::str::FromStr;

use rand::RngCore;
use serde::{Deserialize, Deserializer, Serialize, Serializer};

use crate::errors::{FabricError, FabricResult};

/// Number of bytes in a stable identity.
pub const ID_BYTES: usize = 16;

/// A stable 128-bit identity.
///
/// Identities are generated by the coordinator and are globally stable for the
/// lifetime of the object they name. Workloads and checkpoints never reuse an ID.
#[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct Id([u8; ID_BYTES]);

impl Id {
    /// Generate a new random 128-bit identity.
    pub fn random() -> Self {
        let mut b = [0u8; ID_BYTES];
        rand::thread_rng().fill_bytes(&mut b);
        Self(b)
    }

    /// Build an identity from a 16-byte array.
    pub fn from_bytes(b: [u8; ID_BYTES]) -> Self {
        Self(b)
    }

    /// The underlying bytes.
    pub fn as_bytes(&self) -> &[u8; ID_BYTES] {
        &self.0
    }

    /// Hex encoding (32 lowercase hex characters).
    pub fn to_hex(&self) -> String {
        hex::encode(self.0)
    }

    /// Parse from a hex string of exactly 32 characters.
    pub fn from_hex(s: &str) -> FabricResult<Self> {
        if s.len() != ID_BYTES * 2 {
            return Err(FabricError::InvalidArgument(format!(
                "id must be {} hex chars, got {}",
                ID_BYTES * 2,
                s.len()
            )));
        }
        let bytes = hex::decode(s)
            .map_err(|e| FabricError::InvalidArgument(format!("invalid id hex: {e}")))?;
        let mut out = [0u8; ID_BYTES];
        out.copy_from_slice(&bytes);
        Ok(Self(out))
    }
}

impl fmt::Display for Id {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.to_hex())
    }
}

impl fmt::Debug for Id {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Id({})", self.to_hex())
    }
}

impl FromStr for Id {
    type Err = FabricError;
    fn from_str(s: &str) -> FabricResult<Self> {
        Self::from_hex(s)
    }
}

impl Serialize for Id {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(&self.to_hex())
    }
}

impl<'de> Deserialize<'de> for Id {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let s = String::deserialize(deserializer)?;
        Self::from_hex(&s).map_err(serde::de::Error::custom)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hex_roundtrip() {
        let id = Id::random();
        let hexed = id.to_hex();
        assert_eq!(hexed.len(), 32);
        let back = Id::from_hex(&hexed).unwrap();
        assert_eq!(id, back);
    }

    #[test]
    fn rejects_bad_hex() {
        assert!(Id::from_hex("zz").is_err());
        assert!(Id::from_hex("abc").is_err());
        assert!(Id::from_hex(&"a".repeat(33)).is_err());
    }

    #[test]
    fn serde_roundtrip() {
        let id = Id::random();
        let json = serde_json::to_string(&id).unwrap();
        let back: Id = serde_json::from_str(&json).unwrap();
        assert_eq!(id, back);
    }
}
