//! First-class workload identity.
//!
//! A workload is a long-running execution that may continue across multiple process
//! IDs, nodes, machines, or accelerators while retaining a stable logical identity.
//! Process IDs are never used as workload identity.

use serde::{Deserialize, Serialize};

use crate::checkpoint::ResumabilityClass;
use crate::compatibility::RuntimeCompatibilityDescriptor;
use crate::id::Id;

/// Protection settings applied to a workload's checkpoints.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProtectionSpec {
    /// Number of most recent checkpoint generations that are protected from retirement.
    pub protected_generations: u32,
    /// Whether any checkpoint of this workload may be pinned explicitly.
    pub allow_pin: bool,
}

impl Default for ProtectionSpec {
    fn default() -> Self {
        Self {
            protected_generations: 1,
            allow_pin: true,
        }
    }
}

/// User-supplied specification for creating a workload.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WorkloadSpec {
    /// Stable 128-bit workload identity (generated by the coordinator if absent).
    pub workload_id: Option<Id>,
    /// Owner / authority identity for this workload.
    pub owner: String,
    /// Opaque workload class.
    pub class: String,
    /// Backend class (e.g. "cpu", "cuda", "tpu").
    pub backend_class: String,
    /// Application state schema version.
    pub state_schema_version: u32,
    /// Runtime compatibility descriptor.
    pub runtime: RuntimeCompatibilityDescriptor,
    /// Arbitrary application metadata.
    pub metadata: serde_json::Value,
    /// Checkpoint protection policy.
    pub protection: ProtectionSpec,
    /// Whether this workload allows at most one active execution continuation.
    pub single_active: bool,
}

/// The resumable workload record as maintained by the coordinator.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Workload {
    pub workload_id: Id,
    /// Monotonic workload generation; bumped by restore and rollback.
    pub workload_generation: u64,
    pub owner: String,
    pub class: String,
    pub created_ms: u64,
    /// Execution epoch; bumped by fence, restore, and migration authority changes.
    pub execution_epoch: u64,
    /// Current active node if one has claimed this workload.
    pub active_node: Option<String>,
    pub backend_class: String,
    /// Highest checkpoint generation committed for this workload.
    pub checkpoint_generation: u64,
    /// Parent workload ID when this workload is a fork.
    pub parent_workload: Option<Id>,
    /// Fork generation relative to the parent lineage.
    pub fork_generation: u64,
    /// Policy version applied to this workload.
    pub policy_version: u32,
    pub metadata: serde_json::Value,
    pub state_schema_version: u32,
    pub runtime: RuntimeCompatibilityDescriptor,
    /// Resumability class of the current state.
    pub resumability_class: ResumabilityClass,
    pub protection: ProtectionSpec,
    pub single_active: bool,
    /// Fencing token; authority to act as the active continuation.
    pub fence_token: Option<String>,
    /// Fencing epoch; any actor with a lower epoch is stale.
    pub fence_epoch: u64,
}

impl Workload {
    /// Whether this workload is currently fenced (no active continuation).
    pub fn is_fenced(&self) -> bool {
        self.fence_token.is_none() || self.active_node.is_none()
    }

    /// Validate that an actor's fence token is still current.
    pub fn validate_fence(&self, actor: &str, token: &str) -> Result<(), String> {
        if self.active_node.as_deref() != Some(actor) {
            return Err(format!(
                "actor {actor} is not the active continuation {:?}",
                self.active_node
            ));
        }
        match &self.fence_token {
            None => Err("workload has no active authority".to_string()),
            Some(t) => {
                if t != token {
                    Err(format!(
                        "stale fence token from {actor}; workload is fenced by another continuation"
                    ))
                } else {
                    Ok(())
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn spec() -> WorkloadSpec {
        WorkloadSpec {
            workload_id: None,
            owner: "test".into(),
            class: "demo".into(),
            backend_class: "cpu".into(),
            state_schema_version: 1,
            runtime: RuntimeCompatibilityDescriptor::local_default(),
            metadata: serde_json::json!({}),
            protection: ProtectionSpec::default(),
            single_active: true,
        }
    }

    #[test]
    fn fence_validation() {
        let mut w = Workload {
            workload_id: Id::random(),
            workload_generation: 0,
            owner: "test".into(),
            class: "demo".into(),
            created_ms: 0,
            execution_epoch: 0,
            active_node: Some("n1".into()),
            backend_class: "cpu".into(),
            checkpoint_generation: 0,
            parent_workload: None,
            fork_generation: 0,
            policy_version: 1,
            metadata: serde_json::json!({}),
            state_schema_version: 1,
            runtime: RuntimeCompatibilityDescriptor::local_default(),
            resumability_class: ResumabilityClass::Equivalent,
            protection: ProtectionSpec::default(),
            single_active: true,
            fence_token: Some("tok".into()),
            fence_epoch: 1,
        };
        assert!(!w.is_fenced());
        assert!(w.validate_fence("n1", "tok").is_ok());
        assert!(w.validate_fence("n1", "bad").is_err());
        w.fence_token = None;
        assert!(w.is_fenced());
    }

    #[test]
    fn spec_is_serializable() {
        let s = spec();
        let json = serde_json::to_string(&s).unwrap();
        let back: WorkloadSpec = serde_json::from_str(&json).unwrap();
        assert_eq!(s, back);
    }
}
